#!/bin/bash

#/ NAME
#/     shocco -- wrapper for shocco to find Markdown.pl, pygmentize
#/
#/ SYNOPSIS
#/     shocco files...

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# find pygmentize from pygments.rb
PATH=$PATH:$(bundle show  pygments.rb)/vendor/pygments-main:$shome/libexec

# execute the rocco gem wrapper with redcarpet compat
exec bundle exec "$shome/libexec/rocco" "$@"
